+incdir+../04_testbench
+incdir+../00_src/Defines
../00_src/Fetch_stage/rtl/program_counter.v
../00_src/Fetch_stage/rtl/IMEM.v
../00_src/Fetch_stage/rtl/IF_stage.v
../00_src/Decode_stage/rtl/control.v
../00_src/Decode_stage/rtl/immediate_generator.v
../00_src/Decode_stage/rtl/register_file.v
../00_src/Decode_stage/rtl/ID_stage.v
../00_src/Execute_stage/rtl/ALU.v
../00_src/Execute_stage/rtl/ALU_control.v
../00_src/Execute_stage/rtl/comparator.v
../00_src/Execute_stage/rtl/EXE_stage.v
../00_src/Memory_stage/rtl/DMEM.v
../00_src/Memory_stage/rtl/MEM_stage.v
../00_src/Top/rtl/hazard_detection.v
../00_src/Top/rtl/forwarding.v
../00_src/Top/rtl/RISCV.v
../04_testbench/RISCV32I_tb.sv
../04_testbench/RISCV32I_regression_tb.sv
