module ID_if(
    input  logic        clk_i,
    input  logic        rstn_i,
    input  logic        flush_i,
    input  logic [31:0] instruction_i,
    input  logic [31:0] addr_current_i,
    input  logic [31:0] write_back_data_i,
    input  logic [4:0]  write_rd_i,
    input  logic        write_en_ID_i,
    input  logic        hz_ctrl_i,
    input  logic        reg_write_en_i,
    output logic        ctrl_branch_o,
    output logic        ctrl_mem_read_o,
    output logic        ctrl_mem_to_reg_o,
    output logic        ctrl_mem_write_o,
    output logic        ctrl_reg_write_o,
    output logic [1:0]  ctrl_ALUOp_o,
    output logic [6:0]  opcode_o,
    output logic [31:0] rd1_o,
    output logic [31:0] rd2_o,
    output logic [31:0] addr_current_o,
    output logic [31:0] imm_gen_o,
    output logic        funct7_30_o,
    output logic [2:0]  funct3_o,
    output logic [4:0]  rs1_o,
    output logic [4:0]  rs2_o,
    output logic [4:0]  write_rd_o
);

    ID_stage ID_stage_inst0(
        .clk_i             (clk_i),
        .rstn_i            (rstn_i),
        .flush_i           (flush_i),
        .instruction_i     (instruction_i),
        .addr_current_i    (addr_current_i),
        .write_back_data_i (write_back_data_i),
        .write_rd_i        (write_rd_i),
        .write_en_ID_i     (write_en_ID_i),
        .hz_ctrl_i         (hz_ctrl_i),
        .reg_write_en_i    (reg_write_en_i),
        .ctrl_branch_o     (ctrl_branch_o),
        .ctrl_mem_read_o   (ctrl_mem_read_o),
        .ctrl_mem_to_reg_o (ctrl_mem_to_reg_o),
        .ctrl_mem_write_o  (ctrl_mem_write_o),
        .ctrl_reg_write_o  (ctrl_reg_write_o),
        .ctrl_ALUOp_o      (ctrl_ALUOp_o),
        .opcode_o          (opcode_o),
        .rd1_o             (rd1_o),
        .rd2_o             (rd2_o),
        .addr_current_o    (addr_current_o),
        .imm_gen_o         (imm_gen_o),
        .funct7_30_o       (funct7_30_o),
        .funct3_o          (funct3_o),
        .rs1_o             (rs1_o),
        .rs2_o             (rs2_o),
        .write_rd_o        (write_rd_o)
    );

endmodule
