module EXE_if(
    input  logic        clk_i,
    input  logic        rstn_i,
    input  logic        ctrl_branch_i,
    input  logic        ctrl_mem_read_i,
    input  logic        ctrl_mem_to_reg_i,
    input  logic        ctrl_mem_write_i,
    input  logic        ctrl_reg_write_i,
    input  logic [1:0]  ctrl_ALUOp_i,
    input  logic [6:0]  opcode_i,
    input  logic [31:0] addr_current_i,
    input  logic [31:0] rd1_i,
    input  logic [31:0] rd2_i,
    input  logic [31:0] imm_gen_i,
    input  logic        funct7_30_i,
    input  logic [2:0]  funct3_i,
    input  logic [31:0] forward_EXMEM_data_i,
    input  logic [31:0] forward_MEMWB_data_i,
    input  logic [1:0]  hz_sel_ALU1_i,
    input  logic [1:0]  hz_sel_ALU2_i,
    input  logic [4:0]  write_rd_i,
    output logic        ctrl_mem_read_o,
    output logic        ctrl_mem_to_reg_o,
    output logic        ctrl_mem_write_o,
    output logic        ctrl_reg_write_o,
    output logic [31:0] addr_branch_o,
    output logic        is_branch_o,
    output logic [31:0] ALUresult_o,
    output logic [31:0] ALU2_i_o,
    output logic [2:0]  funct3_o,
    output logic [4:0]  write_rd_o
);

    EXE_stage EXE_stage_inst0(
        .clk_i                (clk_i),
        .rstn_i               (rstn_i),
        .ctrl_branch_i        (ctrl_branch_i),
        .ctrl_mem_read_i      (ctrl_mem_read_i),
        .ctrl_mem_to_reg_i    (ctrl_mem_to_reg_i),
        .ctrl_mem_write_i     (ctrl_mem_write_i),
        .ctrl_reg_write_i     (ctrl_reg_write_i),
        .ctrl_ALUOp_i         (ctrl_ALUOp_i),
        .opcode_i             (opcode_i),
        .addr_current_i       (addr_current_i),
        .rd1_i                (rd1_i),
        .rd2_i                (rd2_i),
        .imm_gen_i            (imm_gen_i),
        .funct7_30_i          (funct7_30_i),
        .funct3_i             (funct3_i),
        .forward_EXMEM_data_i (forward_EXMEM_data_i),
        .forward_MEMWB_data_i (forward_MEMWB_data_i),
        .hz_sel_ALU1_i        (hz_sel_ALU1_i),
        .hz_sel_ALU2_i        (hz_sel_ALU2_i),
        .write_rd_i           (write_rd_i),
        .ctrl_mem_read_o      (ctrl_mem_read_o),
        .ctrl_mem_to_reg_o    (ctrl_mem_to_reg_o),
        .ctrl_mem_write_o     (ctrl_mem_write_o),
        .ctrl_reg_write_o     (ctrl_reg_write_o),
        .addr_branch_o        (addr_branch_o),
        .is_branch_o          (is_branch_o),
        .ALUresult_o          (ALUresult_o),
        .ALU2_i_o             (ALU2_i_o),
        .funct3_o             (funct3_o),
        .write_rd_o           (write_rd_o)
    );

endmodule
